name: push image

on:
  schedule:
    - cron: '0 0 * * 1'
  push:
    tags:
      - '*'
  workflow_dispatch:

env:
  IMAGE_NAME: dobolinux/iw4x-server
  IMAGE_VERSION: "1.1"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.0.0

      - uses: actions/checkout@v3

      - name: Log into registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: set release date
        run: |
          echo "RELEASE_DATE=$(date --rfc-3339=date)" >> ${GITHUB_ENV}

      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.IMAGE_NAME }}
          tags: |
            latest
            ${{ env.IMAGE_VERSION }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v3.0.0
        with:
          context: ./image
          push: true
          tags: '${{ steps.meta.outputs.tags }}'
          build-args: |
            BUILD_DATE=${{env.RELEASE_DATE }}
            VERSION=${{ env.IMAGE_VERSION }}
      
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ env.IMAGE_NAME }}
          readme-filepath: ./README.md